### PR TITLE
Revert "[exercises/bob] Mention linebreak handling (#285)"

### PR DESCRIPTION
**Pull request by IsaacG**
This reverts commit 36f6951a16dfb7d3a256fc66391cb3aa45ed9cbb.

### CODE REVIEW

**Comment by IsaacG** [comment]
+cc @glennj

**Comment by IsaacG** [comment]
+cc @oleks

**Comment by oleks** [comment]
I agree, but only because it is better to update the global description, and not have this in an awk-specific addendum.

**Comment by oleks** [comment]
> I agree, but only because it is better to update the global description, and not have this in an awk-specific addendum.

https://github.com/exercism/problem-specifications/pull/2489

**Review by glennj — APPROVED** [review]

**Pull request merged**
